//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Admin
{


    public partial class ManageIssues
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.DropDownList ddlBooks;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvBooks;
        protected global::System.Web.UI.WebControls.DropDownList ddlMembers;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMembers;
        protected global::System.Web.UI.WebControls.TextBox txtDueDate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDueDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlEmployees;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmployees;
        protected global::System.Web.UI.WebControls.TextBox txtLateFee;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revLateFee;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Button btnAdd;
        protected global::System.Web.UI.WebControls.Button btnUpdate;
        protected global::System.Web.UI.WebControls.GridView gvIssues;
    }
}
