//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Admin
{
    public partial class ManageIssues
    {
        /// <summary>
        /// Form declaration
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Label for Message
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// DropDownList for Books
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlBooks;

        /// <summary>
        /// RequiredFieldValidator for Books
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvBooks;

        /// <summary>
        /// DropDownList for Members
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMembers;

        /// <summary>
        /// RequiredFieldValidator for Members
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMembers;

        /// <summary>
        /// TextBox for Issue Date
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtIssueDate;

        /// <summary>
        /// RequiredFieldValidator for Issue Date
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvIssueDate;

        /// <summary>
        /// TextBox for Return Date
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtReturnDate;

        /// <summary>
        /// RequiredFieldValidator for Return Date
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvReturnDate;

        /// <summary>
        /// Button for Add Issue
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAdd;

        /// <summary>
        /// Button for Clear Fields
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;

        /// <summary>
        /// GridView for displaying issues
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvIssues;
    }
}