//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Admin
{
    public partial class ManageEmployees
    {
        /// <summary>
        /// Form declaration
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Label for Message
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// TextBox for Full Name
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>
        /// RequiredFieldValidator for Full Name
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;

        /// <summary>
        /// TextBox for Position
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPosition;

        /// <summary>
        /// RequiredFieldValidator for Position
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPosition;

        /// <summary>
        /// TextBox for Hire Date
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtHireDate;

        /// <summary>
        /// RequiredFieldValidator for Hire Date
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvHireDate;

        /// <summary>
        /// Button for Add Employee
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAdd;

        /// <summary>
        /// Button for Update Employee
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdate;

        /// <summary>
        /// GridView for displaying employees
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvEmployees;
    }
}