//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Admin
{
    public partial class ManageCategories
    {
        /// <summary>
        /// Form declaration
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Label for Message
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// TextBox for Category Name
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCategoryName;

        /// <summary>
        /// RequiredFieldValidator for Category Name
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCategoryName;

        /// <summary>
        /// Button for Add Category
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAdd;

        /// <summary>
        /// Button for Update Category
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdate;

        /// <summary>
        /// GridView for displaying categories
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvCategories;
    }
}