//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Admin
{
    public partial class ManageBooks
    {
        /// <summary>
        /// Form declaration
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Label for Message
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// TextBox for Title
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        /// <summary>
        /// RequiredFieldValidator for Title
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;

        /// <summary>
        /// TextBox for Author
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAuthor;

        /// <summary>
        /// RequiredFieldValidator for Author
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAuthor;

        /// <summary>
        /// DropDownList for Category
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        /// <summary>
        /// RequiredFieldValidator for Category
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCategory;

        /// <summary>
        /// TextBox for Quantity
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQuantity;

        /// <summary>
        /// RequiredFieldValidator for Quantity
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQuantity;

        /// <summary>
        /// RegularExpressionValidator for Quantity
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revQuantity;

        /// <summary>
        /// Button for Add Book
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAdd;

        /// <summary>
        /// Button for Update Book
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnUpdate;

        /// <summary>
        /// GridView for displaying books
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvBooks;
    }
}